#!/usr/bin/env bash
#
# Run helper script
# Version: 1.0

set -eo pipefail
IFS=$'\n\t'

__root="$(dirname "$(realpath "$0")")"

source "${__root}"/../_lib/cli.sh

function cmd_up() {
    kubectl apply -f resources/namespace.yaml
    kubectl apply -f resources/volume.yaml
    kubectl apply -f resources/service.yaml
    kubectl apply -f resources/deployment.yaml
}

function cmd_down() {
    kubectl delete -f resources/namespace.yaml
    kubectl delete -f resources/volume.yaml
    kubectl delete -f resources/service.yaml
    kubectl delete -f resources/deployment.yaml
}

function cmd_pause() {
    kubectl delete -f resources/service.yaml
    kubectl delete -f resources/deployment.yaml
}

function cmd_help() {
    echo "Usage: $0 {up|down|pause}"
}

main "$@"
